/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2017-09-10 00:32:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import beans.User;
import DB.DBconnection;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/includesPage/footer.jsp", Long.valueOf(1457390384688L));
    _jspx_dependants.put("/includesPage/navbar.jsp", Long.valueOf(1458349053868L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1460086295113L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("DB.DBconnection");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("beans.User");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/mystyle.css\" />\r\n");
      out.write("<title>MyShoppingSite</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"myheader\" class=\"row\">\r\n");
      out.write("\t\t<div class=container>\r\n");
      out.write("\t\t\t<div class=\"col-xs-8\">\r\n");
      out.write("\t\t\t\t<a href=\"index.jsp\"><img src=\"images/MyShoppingSite.png\" height=\"80px\" width=\"250px\"\r\n");
      out.write("\t\t\t\t\tclass=\"img-responsive\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"mybuttons\" class=\"col-xs-4 pull-right\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<a href=\"viewcart.jsp\">Cart</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								
				        		if (session.getAttribute("user") == null ){// THen new user, show join now
				        			
				        			System.out.println("Usersession OFF" + session.getAttribute("user"));
				            
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includesPage/LoginRegister.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

				        }else {
				        	System.out.println("Usersession ON" + session.getAttribute("user"));
				        	
				            
      out.write("\r\n");
      out.write("\t\t\t\t            \r\n");
      out.write("\t\t\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includesPage/logout.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

				        }
				        
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" href=\"#\">All Products <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Computers</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Mobile Devices</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Electronics</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Accessories</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Shocking Deals</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Services</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Contact Us</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<h3 id=\"hottestheadline\">Today's Hottest</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"contentrow\" class=\"hottest row\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t<div class=\"myfooter container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t<h6>Coyright &copy; 2015 MyShoppingSite All rights reserved to\r\n");
      out.write("\t\t\t\t\tVictor De Los Santos</h6>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<h6>Follow us on</h6>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</footer>");
      out.write('\r');
      out.write('\n');
      out.write('	');

		String[][] myarrayofstrings = new String[6][5];

		try {
			
			DBconnection myconn = new DBconnection();
			Connection conn = myconn.getConnection();
			Statement myStmt = conn.createStatement();
			ResultSet myRs = myStmt.executeQuery("select * from products");

			int i = 0;
			while (myRs.next()) {
				for (int j = 0; j < 5; j++) {
					//System.out.println(myRs.getObject(j + 1));
					if (j == 0) {
						myarrayofstrings[i][j] = Integer.toString(myRs.getInt(j + 1));
					} else {
						myarrayofstrings[i][j] = myRs.getString(j + 1);
					}
					
				}
				i++;
			}

		} catch (Exception e) {
			System.out.println("error while accesing db");
			throw new Error(e);
		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\r\n");
      out.write("\tvar content = document.getElementsByClassName(\"hottest row\")[0];\r\n");
      out.write("\t\r\n");
      out.write("\tfunction createnewitem(ID, image, description, price, title){\r\n");
      out.write("\tvar newitem = document.createElement(\"div\");\r\n");
      out.write("\tvar newitemanchor = document.createElement(\"a\");\r\n");
      out.write("\tvar newimage = document.createElement(\"img\");\r\n");
      out.write("\tvar newdescription = document.createElement(\"p\");\r\n");
      out.write("\tvar node = document.createTextNode(title);\r\n");
      out.write("\t//content.setAttribute(\"class\",\"col-xs-4\");\r\n");
      out.write("\t\r\n");
      out.write("\tnewimage.src = image;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tnewimage.setAttribute(\"class\",\"img-responsive\");\r\n");
      out.write("\tnewdescription.appendChild(node);\r\n");
      out.write("\tnewitemanchor.setAttribute(\"href\",\"");
      out.print(request.getContextPath()+"/ViewItemServlet?id=");
      out.write("\"+ID);\r\n");
      out.write("\tnewitemanchor.setAttribute(\"class\",\"thumbnail\");\r\n");
      out.write("\tnewitemanchor.appendChild(newimage);\r\n");
      out.write("\tnewitem.appendChild(newitemanchor);\r\n");
      out.write("\tnewitem.appendChild(newdescription);\r\n");
      out.write("\tnewitem.setAttribute(\"class\",\"item col-sm-4 \");\r\n");
      out.write("\tcontent.appendChild(newitem);\r\n");
      out.write("\t}\r\n");
      out.write("\t");
for (int s = 0; s < 6; s++) {
      out.write("\r\n");
      out.write("\t\tcreatenewitem(\"");
      out.print(myarrayofstrings[s][0]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(myarrayofstrings[s][1]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(myarrayofstrings[s][2]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(myarrayofstrings[s][3]);
      out.write('"');
      out.write(',');
      out.write('"');
      out.print(myarrayofstrings[s][4]);
      out.write("\");\r\n");
      out.write("\t");
}
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
